package org.fxt.freexmltoolkit.controls.v2.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.fxt.freexmltoolkit.controls.v2.editor.serialization.XsdSerializer;
import org.fxt.freexmltoolkit.service.xsd.ParsedSchema;
import org.fxt.freexmltoolkit.service.xsd.XsdParseOptions;
import org.fxt.freexmltoolkit.service.xsd.XsdParsingService;
import org.fxt.freexmltoolkit.service.xsd.XsdParsingServiceImpl;
import org.fxt.freexmltoolkit.service.xsd.adapters.XsdModelAdapter;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Tests for source-only {@code xs:appinfo} elements — the self-closing form
 * {@code <xs:appinfo source="@since 4.2.8"/>} used throughout FundsXML and recommended by the
 * user documentation. The JavaDoc-style tag lives in the {@code source} attribute only, with no
 * text content, and must survive parsing, editing and serialization.
 */
@DisplayName("Source-only xs:appinfo (JavaDoc tags in @source)")
class XsdAppInfoSourceOnlyTest {

    private static final String SCHEMA_WITH_SOURCE_ONLY_APPINFO = """
            <?xml version="1.0" encoding="UTF-8"?>
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
              <xs:element name="Transaction">
                <xs:annotation>
                  <xs:documentation>A single financial transaction.</xs:documentation>
                  <xs:appinfo source="@since 4.2.8"/>
                  <xs:appinfo source="@see {@link /FundsXML4/ControlData}"/>
                  <xs:appinfo source="@deprecated Use NewTransaction instead."/>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence/>
                </xs:complexType>
              </xs:element>
            </xs:schema>
            """;

    @Test
    @DisplayName("XsdNodeFactory keeps the JavaDoc tags of a source-only appinfo")
    void nodeFactoryKeepsSourceOnlyTags() throws Exception {
        XsdSchema schema = new XsdNodeFactory().fromString(SCHEMA_WITH_SOURCE_ONLY_APPINFO);

        XsdAppInfo appinfo = firstElement(schema).getAppinfo();
        assertNotNull(appinfo, "the element must carry the appinfo of its annotation");
        assertEquals("4.2.8", appinfo.getSince());
        assertEquals(List.of("{@link /FundsXML4/ControlData}"), appinfo.getSeeReferences());
        assertEquals("Use NewTransaction instead.", appinfo.getDeprecated());
    }

    @Test
    @DisplayName("XsdModelAdapter keeps the JavaDoc tags of a source-only appinfo")
    void modelAdapterKeepsSourceOnlyTags() throws Exception {
        XsdParsingService parsingService = new XsdParsingServiceImpl();
        ParsedSchema parsed = parsingService.parse(SCHEMA_WITH_SOURCE_ONLY_APPINFO, null, XsdParseOptions.defaults());
        XsdSchema schema = new XsdModelAdapter(XsdParseOptions.defaults()).toXsdModel(parsed);

        XsdAppInfo appinfo = firstElement(schema).getAppinfo();
        assertNotNull(appinfo, "the element must carry the appinfo of its annotation");
        assertEquals("4.2.8", appinfo.getSince());
        assertEquals(List.of("{@link /FundsXML4/ControlData}"), appinfo.getSeeReferences());
        assertEquals("Use NewTransaction instead.", appinfo.getDeprecated());
    }

    @Test
    @DisplayName("A managed tag serializes as a self-closing appinfo without duplicated text")
    void managedTagSerializesAsSelfClosingAppinfo() {
        XsdAppInfo appinfo = new XsdAppInfo();
        appinfo.setSince("4.2.8");
        appinfo.addSeeReference("{@link /FundsXML4/ControlData}");
        appinfo.setDeprecated("Use NewTransaction instead.");

        List<String> xml = appinfo.toXmlStrings();

        assertEquals(List.of(
                "<xs:appinfo source=\"@since 4.2.8\"/>",
                "<xs:appinfo source=\"@see {@link /FundsXML4/ControlData}\"/>",
                "<xs:appinfo source=\"@deprecated Use NewTransaction instead.\"/>"), xml);
    }

    @Test
    @DisplayName("Text content that differs from the source attribute is preserved")
    void distinctTextContentIsPreserved() {
        XsdAppInfo appinfo = new XsdAppInfo();
        appinfo.addEntry("urn:example:tooling", "generated by the mapping tool");

        List<String> xml = appinfo.toXmlStrings();

        assertEquals(List.of("<xs:appinfo source=\"urn:example:tooling\">generated by the mapping tool</xs:appinfo>"),
                xml);
    }

    @Test
    @DisplayName("Round trip keeps the documented self-closing form")
    void roundTripKeepsSelfClosingForm() throws Exception {
        XsdSchema schema = new XsdNodeFactory().fromString(SCHEMA_WITH_SOURCE_ONLY_APPINFO);

        String serialized = new XsdSerializer().serialize(schema);

        assertTrue(serialized.contains("<xs:appinfo source=\"@since 4.2.8\"/>"),
                "the @since tag must round trip in its self-closing form, was:\n" + serialized);
        assertFalse(serialized.contains(">@since"),
                "the tag must not be duplicated into the text content, was:\n" + serialized);
    }

    private static XsdElement firstElement(XsdSchema schema) {
        assertNotNull(schema, "schema must parse");
        return schema.getChildren().stream()
                .filter(XsdElement.class::isInstance)
                .map(XsdElement.class::cast)
                .findFirst()
                .orElseThrow(() -> new AssertionError("no top-level element in the parsed schema"));
    }
}
