package org.fxt.freexmltoolkit.controls.v2.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.fxt.freexmltoolkit.controls.v2.editor.serialization.XsdSerializer;
import org.fxt.freexmltoolkit.service.xsd.ParsedSchema;
import org.fxt.freexmltoolkit.service.xsd.XsdParseOptions;
import org.fxt.freexmltoolkit.service.xsd.XsdParsingService;
import org.fxt.freexmltoolkit.service.xsd.XsdParsingServiceImpl;
import org.fxt.freexmltoolkit.service.xsd.adapters.XsdModelAdapter;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Tests for the legacy source-only {@code xs:appinfo} form
 * {@code <xs:appinfo source="@since 4.2.8"/>} used throughout FundsXML: the JavaDoc-style tag and
 * its value both live in the {@code source} attribute. It must still parse, and it is migrated to
 * the canonical {@code <xs:appinfo source="@since">4.2.8</xs:appinfo>} form on serialization.
 */
@DisplayName("Legacy source-only xs:appinfo (tag and value in @source)")
class XsdAppInfoSourceOnlyTest {

    private static final String SCHEMA_WITH_SOURCE_ONLY_APPINFO = """
            <?xml version="1.0" encoding="UTF-8"?>
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
              <xs:element name="Transaction">
                <xs:annotation>
                  <xs:documentation>A single financial transaction.</xs:documentation>
                  <xs:appinfo source="@since 4.2.8"/>
                  <xs:appinfo source="@see {@link /FundsXML4/ControlData}"/>
                  <xs:appinfo source="@deprecated Use NewTransaction instead."/>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence/>
                </xs:complexType>
              </xs:element>
            </xs:schema>
            """;

    @Test
    @DisplayName("XsdNodeFactory keeps the JavaDoc tags of a source-only appinfo")
    void nodeFactoryKeepsSourceOnlyTags() throws Exception {
        XsdSchema schema = new XsdNodeFactory().fromString(SCHEMA_WITH_SOURCE_ONLY_APPINFO);

        XsdAppInfo appinfo = firstElement(schema).getAppinfo();
        assertNotNull(appinfo, "the element must carry the appinfo of its annotation");
        assertEquals("4.2.8", appinfo.getSince());
        assertEquals(List.of("{@link /FundsXML4/ControlData}"), appinfo.getSeeReferences());
        assertEquals("Use NewTransaction instead.", appinfo.getDeprecated());
    }

    @Test
    @DisplayName("XsdModelAdapter keeps the JavaDoc tags of a source-only appinfo")
    void modelAdapterKeepsSourceOnlyTags() throws Exception {
        XsdParsingService parsingService = new XsdParsingServiceImpl();
        ParsedSchema parsed = parsingService.parse(SCHEMA_WITH_SOURCE_ONLY_APPINFO, null, XsdParseOptions.defaults());
        XsdSchema schema = new XsdModelAdapter(XsdParseOptions.defaults()).toXsdModel(parsed);

        XsdAppInfo appinfo = firstElement(schema).getAppinfo();
        assertNotNull(appinfo, "the element must carry the appinfo of its annotation");
        assertEquals("4.2.8", appinfo.getSince());
        assertEquals(List.of("{@link /FundsXML4/ControlData}"), appinfo.getSeeReferences());
        assertEquals("Use NewTransaction instead.", appinfo.getDeprecated());
    }

    @Test
    @DisplayName("A managed tag serializes with the tag in @source and the value as text")
    void managedTagSerializesInTheCanonicalForm() {
        XsdAppInfo appinfo = new XsdAppInfo();
        appinfo.setSince("4.2.8");
        appinfo.addSeeReference("{@link /FundsXML4/ControlData}");
        appinfo.setDeprecated("Use NewTransaction instead.");

        List<String> xml = appinfo.toXmlStrings();

        assertEquals(List.of(
                "<xs:appinfo source=\"@since\">4.2.8</xs:appinfo>",
                "<xs:appinfo source=\"@see\">{@link /FundsXML4/ControlData}</xs:appinfo>",
                "<xs:appinfo source=\"@deprecated\">Use NewTransaction instead.</xs:appinfo>"), xml);
    }

    @Test
    @DisplayName("Text content that differs from the source attribute is preserved")
    void distinctTextContentIsPreserved() {
        XsdAppInfo appinfo = new XsdAppInfo();
        appinfo.addEntry("urn:example:tooling", "generated by the mapping tool");

        List<String> xml = appinfo.toXmlStrings();

        assertEquals(List.of("<xs:appinfo source=\"urn:example:tooling\">generated by the mapping tool</xs:appinfo>"),
                xml);
    }

    @Test
    @DisplayName("Round trip migrates the legacy form to the canonical one")
    void roundTripMigratesToTheCanonicalForm() throws Exception {
        XsdSchema schema = new XsdNodeFactory().fromString(SCHEMA_WITH_SOURCE_ONLY_APPINFO);

        String serialized = new XsdSerializer().serialize(schema);

        assertTrue(serialized.contains("<xs:appinfo source=\"@since\">4.2.8</xs:appinfo>"),
                "the @since tag must be written in the canonical form, was:\n" + serialized);
        assertFalse(serialized.contains("source=\"@since 4.2.8\""),
                "the legacy form must not survive a save, was:\n" + serialized);
        assertFalse(serialized.contains(">@since"),
                "the tag must not be duplicated into the text content, was:\n" + serialized);
    }

    private static XsdElement firstElement(XsdSchema schema) {
        assertNotNull(schema, "schema must parse");
        return schema.getChildren().stream()
                .filter(XsdElement.class::isInstance)
                .map(XsdElement.class::cast)
                .findFirst()
                .orElseThrow(() -> new AssertionError("no top-level element in the parsed schema"));
    }
}
