package org.fxt.freexmltoolkit.controls.v2.editor.statistics.report;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.sax.SAXResult;
import javax.xml.transform.stream.StreamSource;

import org.apache.fop.apps.FOUserAgent;
import org.apache.fop.apps.Fop;
import org.apache.fop.apps.FopFactory;
import org.apache.fop.apps.MimeConstants;
import org.fxt.freexmltoolkit.util.SecureXmlFactory;

/**
 * PDF rendering through Apache FOP (XSL-FO). Fixed table layout with proportional column
 * widths (FOP has no auto layout), zero-width break opportunities inside long tokens (XPaths,
 * URIs) so cells never overflow, and a "(none)" block instead of an empty table body, which
 * FOP rejects.
 */
public final class PdfReportWriter implements ReportWriter {

    private static volatile FopFactory fopFactory;

    @Override
    public void write(ReportModel model, Path target) throws IOException {
        String fo = toXslFo(model);
        try {
            FopFactory factory = factory();
            FOUserAgent agent = factory.newFOUserAgent();
            ReportMetadata.service().setPdfMetadata(agent, model.title());
            try (OutputStream out = new BufferedOutputStream(Files.newOutputStream(target))) {
                Fop fop = factory.newFop(MimeConstants.MIME_PDF, agent, out);
                TransformerFactory transformerFactory = SecureXmlFactory.createSecureTransformerFactory();
                Transformer transformer = transformerFactory.newTransformer();
                Source source = new StreamSource(new StringReader(fo));
                Result result = new SAXResult(fop.getDefaultHandler());
                transformer.transform(source, result);
            }
        } catch (IOException e) {
            throw e;
        } catch (Exception e) {
            throw new IOException("Failed to render PDF: " + e.getMessage(), e);
        }
    }

    private static FopFactory factory() {
        FopFactory local = fopFactory;
        if (local == null) {
            synchronized (PdfReportWriter.class) {
                local = fopFactory;
                if (local == null) {
                    local = FopFactory.newInstance(new File(".").toURI());
                    fopFactory = local;
                }
            }
        }
        return local;
    }

    /** The XSL-FO document for {@code model} (package-private for tests). */
    static String toXslFo(ReportModel model) {
        StringBuilder fo = new StringBuilder(16 * 1024);
        fo.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        fo.append("<fo:root xmlns:fo=\"http://www.w3.org/1999/XSL/Format\" font-family=\"Helvetica\" font-size=\"9pt\">\n");
        fo.append("  <fo:layout-master-set>\n");
        fo.append("    <fo:simple-page-master master-name=\"A4\" page-height=\"297mm\" page-width=\"210mm\" ");
        fo.append("margin-top=\"15mm\" margin-bottom=\"15mm\" margin-left=\"18mm\" margin-right=\"18mm\">\n");
        fo.append("      <fo:region-body margin-top=\"10mm\" margin-bottom=\"10mm\"/>\n");
        fo.append("      <fo:region-before extent=\"8mm\"/>\n      <fo:region-after extent=\"8mm\"/>\n");
        fo.append("    </fo:simple-page-master>\n  </fo:layout-master-set>\n");
        fo.append("  <fo:page-sequence master-reference=\"A4\">\n");
        fo.append("    <fo:static-content flow-name=\"xsl-region-before\">\n");
        fo.append("      <fo:block font-size=\"8pt\" text-align=\"center\" color=\"#666666\">")
                .append(escape(model.title())).append(" - Generated by FreeXmlToolkit</fo:block>\n");
        fo.append("    </fo:static-content>\n");
        fo.append("    <fo:static-content flow-name=\"xsl-region-after\">\n");
        fo.append("      <fo:block font-size=\"8pt\" text-align=\"center\" color=\"#666666\">Page <fo:page-number/> · ")
                .append(escape(model.generatedAt().format(ReportWriters.TIMESTAMP))).append("</fo:block>\n");
        fo.append("    </fo:static-content>\n");
        fo.append("    <fo:flow flow-name=\"xsl-region-body\">\n");
        fo.append("      <fo:block font-size=\"18pt\" font-weight=\"bold\" color=\"#2c3e50\" space-after=\"2mm\">")
                .append(escape(model.title())).append("</fo:block>\n");
        if (!model.subject().isBlank()) {
            fo.append("      <fo:block font-size=\"10pt\" color=\"#555555\" space-after=\"1mm\">")
                    .append(breakable(escape(model.subject()))).append("</fo:block>\n");
        }
        fo.append("      <fo:block font-size=\"8pt\" color=\"#7f8c8d\" space-after=\"6mm\">Generated: ")
                .append(escape(model.generatedAt().format(ReportWriters.TIMESTAMP))).append("</fo:block>\n");

        for (ReportSection section : model.sections()) {
            fo.append("      <fo:block font-size=\"13pt\" font-weight=\"bold\" color=\"#34495e\" space-before=\"6mm\" space-after=\"2mm\" ")
                    .append("border-bottom=\"0.5pt solid #bdc3c7\" padding-bottom=\"1mm\" keep-with-next=\"always\">")
                    .append(escape(section.title())).append("</fo:block>\n");
            if (!section.facts().isEmpty()) {
                fo.append("      <fo:table table-layout=\"fixed\" width=\"100%\" space-after=\"3mm\">\n");
                fo.append("        <fo:table-column column-width=\"proportional-column-width(1)\"/>\n");
                fo.append("        <fo:table-column column-width=\"proportional-column-width(2)\"/>\n");
                fo.append("        <fo:table-body>\n");
                for (KeyValue fact : section.facts()) {
                    fo.append("          <fo:table-row>\n");
                    cell(fo, escape(fact.key()), "#555555", null, false);
                    cell(fo, breakable(escape(fact.value())),
                            fact.tone() == Tone.NONE ? null : fact.tone().foreground(), null, fact.tone() != Tone.NONE);
                    fo.append("          </fo:table-row>\n");
                }
                fo.append("        </fo:table-body>\n      </fo:table>\n");
            }
            for (ReportTable table : section.tables()) {
                fo.append("      <fo:block font-size=\"10pt\" font-weight=\"bold\" color=\"#34495e\" space-before=\"3mm\" space-after=\"1mm\" keep-with-next=\"always\">")
                        .append(escape(table.title())).append("</fo:block>\n");
                if (table.isEmpty()) {
                    fo.append("      <fo:block font-style=\"italic\" color=\"#999999\" space-after=\"2mm\">(none)</fo:block>\n");
                    continue;
                }
                List<String> headers = table.headers();
                String fontSize = headers.size() > 6 ? "6.5pt" : headers.size() > 4 ? "7.5pt" : "8.5pt";
                fo.append("      <fo:table table-layout=\"fixed\" width=\"100%\" font-size=\"").append(fontSize)
                        .append("\" space-after=\"3mm\" border=\"0.5pt solid #d0d0d0\">\n");
                int[] weights = columnWeights(table);
                for (int weight : weights) {
                    fo.append("        <fo:table-column column-width=\"proportional-column-width(").append(weight).append(")\"/>\n");
                }
                fo.append("        <fo:table-header>\n          <fo:table-row background-color=\"#ecf0f1\">\n");
                for (String header : headers) {
                    cell(fo, escape(header), null, null, true);
                }
                fo.append("          </fo:table-row>\n        </fo:table-header>\n        <fo:table-body>\n");
                for (ReportRow row : table.rows()) {
                    String background = row.tone() == Tone.NONE ? null : row.tone().background();
                    fo.append("          <fo:table-row").append(background != null ? " background-color=\"" + background + "\"" : "").append(">\n");
                    for (String value : row.cells()) {
                        cell(fo, breakable(escape(value)), null, null, false);
                    }
                    fo.append("          </fo:table-row>\n");
                }
                fo.append("        </fo:table-body>\n      </fo:table>\n");
            }
            if (section.note() != null && !section.note().isBlank()) {
                fo.append("      <fo:block font-size=\"8pt\" color=\"#666666\" space-after=\"2mm\">")
                        .append(breakable(escape(section.note()))).append("</fo:block>\n");
            }
        }
        fo.append("    </fo:flow>\n  </fo:page-sequence>\n</fo:root>\n");
        return fo.toString();
    }

    private static void cell(StringBuilder fo, String text, String color, String background, boolean bold) {
        fo.append("            <fo:table-cell padding=\"1.2mm\" border=\"0.3pt solid #e0e0e0\"");
        if (background != null) {
            fo.append(" background-color=\"").append(background).append('"');
        }
        fo.append("><fo:block");
        if (color != null) {
            fo.append(" color=\"").append(color).append('"');
        }
        if (bold) {
            fo.append(" font-weight=\"bold\"");
        }
        fo.append(">").append(text.isEmpty() ? " " : text).append("</fo:block></fo:table-cell>\n");
    }

    /** Column weights from the longest cell per column (clamped 1..6) so wide text gets more room. */
    private static int[] columnWeights(ReportTable table) {
        int[] weights = new int[table.headers().size()];
        for (int i = 0; i < weights.length; i++) {
            int longest = table.headers().get(i).length();
            for (ReportRow row : table.rows()) {
                longest = Math.max(longest, Math.min(row.cells().get(i).length(), 80));
            }
            weights[i] = Math.max(1, Math.min(6, (longest + 9) / 10));
        }
        return weights;
    }

    /** Inserts zero-width spaces after / : . _ and before uppercase runs so long tokens can wrap. */
    static String breakable(String text) {
        if (text == null || text.length() < 24) {
            return text == null ? "" : text;
        }
        StringBuilder sb = new StringBuilder(text.length() + 16);
        int run = 0;
        for (int i = 0; i < text.length(); i++) {
            char c = text.charAt(i);
            sb.append(c);
            run = Character.isWhitespace(c) ? 0 : run + 1;
            if ((c == '/' || c == ':' || c == '.' || c == '_' || c == ';' || c == ',' || c == '=' || c == '@')
                    && i + 1 < text.length() && !Character.isWhitespace(text.charAt(i + 1))) {
                sb.append('​');
                run = 0;
            } else if (run >= 30) {
                sb.append('​');
                run = 0;
            }
        }
        return sb.toString();
    }

    static String escape(String value) {
        if (value == null) {
            return "";
        }
        StringBuilder sb = new StringBuilder(value.length());
        for (char c : value.toCharArray()) {
            switch (c) {
                case '<' -> sb.append("&lt;");
                case '>' -> sb.append("&gt;");
                case '&' -> sb.append("&amp;");
                case '"' -> sb.append("&quot;");
                default -> {
                    if (c < 0x20 && c != '\n' && c != '\t' && c != '\r') {
                        sb.append(' ');
                    } else {
                        sb.append(c);
                    }
                }
            }
        }
        return sb.toString();
    }
}
