<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:fo="http://www.w3.org/1999/XSL/Format">

    <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
    <xsl:strip-space elements="*"/>

    <!-- Key for Asset lookup -->
    <xsl:key name="asset-by-id" match="Asset" use="UniqueID"/>

    <!-- Main template for Portfolio Analysis -->
    <xsl:template match="/FundsXML4">
        <fo:root>
            <!-- Page Layout Definition with Landscape Orientation -->
            <fo:layout-master-set>
                <fo:simple-page-master master-name="portfolio-analysis-page"
                                       page-height="21cm"
                                       page-width="29.7cm"
                                       margin-top="1.5cm"
                                       margin-bottom="1.5cm"
                                       margin-left="2cm"
                                       margin-right="2cm">
                    <fo:region-body margin-top="2cm" margin-bottom="1.5cm"/>
                    <fo:region-before region-name="header" extent="1.5cm"/>
                    <fo:region-after region-name="footer" extent="1cm"/>
                </fo:simple-page-master>
            </fo:layout-master-set>

            <!-- Page Sequence -->
            <fo:page-sequence master-reference="portfolio-analysis-page">
                <!-- Header -->
                <fo:static-content flow-name="header">
                    <fo:block-container background-color="#17a2b8" color="#ffffff" padding="6mm">
                        <fo:table table-layout="fixed" width="100%">
                            <fo:table-column column-width="70%"/>
                            <fo:table-column column-width="30%"/>
                            <fo:table-body>
                                <fo:table-row>
                                    <fo:table-cell>
                                        <fo:block font-size="20pt" font-weight="bold">
                                            📊 PORTFOLIO ANALYSIS REPORT
                                        </fo:block>
                                        <fo:block font-size="10pt" space-before="2mm">
                                            Detailed Holdings Analysis and Position Breakdown
                                        </fo:block>
                                    </fo:table-cell>
                                    <fo:table-cell>
                                        <fo:block text-align="right" font-size="12pt">
                                            <xsl:value-of select="ControlData/ContentDate"/>
                                        </fo:block>
                                        <fo:block text-align="right" font-size="8pt" space-before="1mm">
                                            Document:
                                            <xsl:value-of select="ControlData/UniqueDocumentID"/>
                                        </fo:block>
                                    </fo:table-cell>
                                </fo:table-row>
                            </fo:table-body>
                        </fo:table>
                    </fo:block-container>
                </fo:static-content>

                <!-- Footer -->
                <fo:static-content flow-name="footer">
                    <fo:block text-align="center" font-size="8pt" color="#666666"
                              border-top="0.5pt solid #17a2b8" padding-top="3mm">
                        Page
                        <fo:page-number/>
                        • Generated by FreeXmlToolkit • Data:
                        <xsl:value-of select="ControlData/DataSupplier/Name"/>
                    </fo:block>
                </fo:static-content>

                <!-- Main Content Flow -->
                <fo:flow flow-name="xsl-region-body" font-family="Arial, Helvetica, sans-serif" font-size="9pt">

                    <!-- Portfolio Statistics Overview -->
                    <fo:block-container background-color="#e1f5fe" padding="6mm" space-after="8mm"
                                        border="1pt solid #17a2b8">
                        <fo:block font-size="14pt" font-weight="bold" color="#17a2b8" space-after="4mm">
                            📈 PORTFOLIO STATISTICS OVERVIEW
                        </fo:block>

                        <fo:table table-layout="fixed" width="100%">
                            <fo:table-column column-width="20%"/>
                            <fo:table-column column-width="20%"/>
                            <fo:table-column column-width="20%"/>
                            <fo:table-column column-width="20%"/>
                            <fo:table-column column-width="20%"/>
                            <fo:table-body>
                                <fo:table-row>
                                    <fo:table-cell padding="2mm">
                                        <fo:block-container background-color="#ffffff" padding="4mm"
                                                            border="1pt solid #17a2b8" text-align="center">
                                            <fo:block font-size="8pt" color="#666666" font-weight="bold">FUNDS
                                            </fo:block>
                                            <fo:block font-size="18pt" font-weight="bold" color="#17a2b8">
                                                <xsl:value-of select="count(Funds/Fund)"/>
                                            </fo:block>
                                        </fo:block-container>
                                    </fo:table-cell>
                                    <fo:table-cell padding="2mm">
                                        <fo:block-container background-color="#ffffff" padding="4mm"
                                                            border="1pt solid #17a2b8" text-align="center">
                                            <fo:block font-size="8pt" color="#666666" font-weight="bold">TOTAL
                                                POSITIONS
                                            </fo:block>
                                            <fo:block font-size="18pt" font-weight="bold" color="#17a2b8">
                                                <xsl:value-of select="count(//Position)"/>
                                            </fo:block>
                                        </fo:block-container>
                                    </fo:table-cell>
                                    <fo:table-cell padding="2mm">
                                        <fo:block-container background-color="#ffffff" padding="4mm"
                                                            border="1pt solid #17a2b8" text-align="center">
                                            <fo:block font-size="8pt" color="#666666" font-weight="bold">TOTAL NAV
                                                (EUR)
                                            </fo:block>
                                            <fo:block font-size="14pt" font-weight="bold" color="#17a2b8">
                                                <xsl:value-of
                                                        select="format-number(sum(//TotalNetAssetValue/Amount), '#,##0')"/>M
                                            </fo:block>
                                        </fo:block-container>
                                    </fo:table-cell>
                                    <fo:table-cell padding="2mm">
                                        <fo:block-container background-color="#ffffff" padding="4mm"
                                                            border="1pt solid #17a2b8" text-align="center">
                                            <fo:block font-size="8pt" color="#666666" font-weight="bold">CURRENCIES
                                            </fo:block>
                                            <fo:block font-size="18pt" font-weight="bold" color="#17a2b8">
                                                <xsl:value-of
                                                        select="count(//Position/Currency[generate-id() = generate-id(key('currencies', .)[1])])"/>
                                            </fo:block>
                                        </fo:block-container>
                                    </fo:table-cell>
                                    <fo:table-cell padding="2mm">
                                        <fo:block-container background-color="#ffffff" padding="4mm"
                                                            border="1pt solid #17a2b8" text-align="center">
                                            <fo:block font-size="8pt" color="#666666" font-weight="bold">ANALYSIS DATE
                                            </fo:block>
                                            <fo:block font-size="12pt" font-weight="bold" color="#17a2b8">
                                                <xsl:value-of select="ControlData/ContentDate"/>
                                            </fo:block>
                                        </fo:block-container>
                                    </fo:table-cell>
                                </fo:table-row>
                            </fo:table-body>
                        </fo:table>
                    </fo:block-container>

                    <!-- Individual Fund Analysis -->
                    <xsl:for-each select="Funds/Fund">
                        <fo:block-container space-after="8mm" keep-together.within-page="always">
                            <!-- Fund Header -->
                            <fo:block-container background-color="#6f42c1" color="#ffffff" padding="5mm"
                                                space-after="5mm">
                                <fo:table table-layout="fixed" width="100%">
                                    <fo:table-column column-width="60%"/>
                                    <fo:table-column column-width="40%"/>
                                    <fo:table-body>
                                        <fo:table-row>
                                            <fo:table-cell>
                                                <fo:block font-size="16pt" font-weight="bold">
                                                    💼
                                                    <xsl:value-of select="Names/OfficialName"/>
                                                </fo:block>
                                                <fo:block font-size="9pt" space-before="2mm">
                                                    LEI:
                                                    <xsl:value-of select="Identifiers/LEI"/>
                                                </fo:block>
                                            </fo:table-cell>
                                            <fo:table-cell>
                                                <fo:block text-align="right" font-size="14pt" font-weight="bold">
                                                    <xsl:value-of
                                                            select="format-number(FundDynamicData/TotalAssetValues/TotalAssetValue/TotalNetAssetValue/Amount, '#,##0.00')"/>
                                                    <xsl:text> </xsl:text>
                                                    <xsl:value-of
                                                            select="FundDynamicData/TotalAssetValues/TotalAssetValue/TotalNetAssetValue/Amount/@ccy"/>
                                                </fo:block>
                                                <fo:block text-align="right" font-size="8pt" space-before="1mm">
                                                    <xsl:value-of
                                                            select="count(FundDynamicData/Portfolios/Portfolio/Positions/Position)"/>
                                                    Positions
                                                </fo:block>
                                            </fo:table-cell>
                                        </fo:table-row>
                                    </fo:table-body>
                                </fo:table>
                            </fo:block-container>

                            <!-- Detailed Position Table -->
                            <fo:table table-layout="fixed" width="100%" border-collapse="collapse"
                                      border="1pt solid #dee2e6" space-after="6mm">
                                <fo:table-column column-width="5%"/>   <!-- Rank -->
                                <fo:table-column column-width="20%"/>  <!-- Position ID -->
                                <fo:table-column column-width="12%"/>  <!-- ISIN -->
                                <fo:table-column column-width="8%"/>   <!-- Currency -->
                                <fo:table-column column-width="18%"/>  <!-- Value -->
                                <fo:table-column column-width="10%"/>  <!-- Percentage -->
                                <fo:table-column column-width="12%"/>  <!-- Market Value -->
                                <fo:table-column column-width="15%"/>  <!-- FX Rate -->

                                <fo:table-header background-color="#f8f9fa">
                                    <fo:table-row>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" text-align="center" font-size="8pt">#
                                            </fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt">Position ID</fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt">ISIN</fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt" text-align="center">CCY
                                            </fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt" text-align="right">Total
                                                Value
                                            </fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt" text-align="right">Weight %
                                            </fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt" text-align="right">Market
                                                Value
                                            </fo:block>
                                        </fo:table-cell>
                                        <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                            <fo:block font-weight="bold" font-size="8pt" text-align="center">FX Rate
                                            </fo:block>
                                        </fo:table-cell>
                                    </fo:table-row>
                                </fo:table-header>

                                <fo:table-body>
                                    <xsl:for-each select="FundDynamicData/Portfolios/Portfolio/Positions/Position">
                                        <xsl:sort select="TotalPercentage" data-type="number" order="descending"/>
                                        <fo:table-row>
                                            <xsl:if test="position() mod 2 = 0">
                                                <xsl:attribute name="background-color">#f8f9fa</xsl:attribute>
                                            </xsl:if>

                                            <!-- Rank -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="center" font-size="8pt">
                                                    <xsl:choose>
                                                        <xsl:when test="position() &lt;= 3">
                                                            <xsl:attribute name="color">#dc3545</xsl:attribute>
                                                            <xsl:attribute name="font-weight">bold</xsl:attribute>
                                                        </xsl:when>
                                                        <xsl:when test="position() &lt;= 10">
                                                            <xsl:attribute name="color">#ffc107</xsl:attribute>
                                                            <xsl:attribute name="font-weight">bold</xsl:attribute>
                                                        </xsl:when>
                                                    </xsl:choose>
                                                    <xsl:value-of select="position()"/>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- Position ID -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block font-size="7pt" font-family="Courier, monospace">
                                                    <xsl:value-of select="UniqueID"/>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- ISIN -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block font-size="7pt" font-family="Courier, monospace">
                                                    <xsl:choose>
                                                        <xsl:when test="Identifiers/ISIN">
                                                            <xsl:value-of select="Identifiers/ISIN"/>
                                                        </xsl:when>
                                                        <xsl:when test="Identifiers/OtherID">
                                                            <xsl:value-of
                                                                    select="substring(Identifiers/OtherID, 1, 12)"/>
                                                        </xsl:when>
                                                        <xsl:otherwise>N/A</xsl:otherwise>
                                                    </xsl:choose>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- Currency -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="center" font-size="8pt" font-weight="bold">
                                                    <xsl:choose>
                                                        <xsl:when test="Currency != ../../../../../Currency">
                                                            <xsl:attribute name="color">#dc3545</xsl:attribute>
                                                        </xsl:when>
                                                        <xsl:otherwise>
                                                            <xsl:attribute name="color">#28a745</xsl:attribute>
                                                        </xsl:otherwise>
                                                    </xsl:choose>
                                                    <xsl:value-of select="Currency"/>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- Total Value -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="right" font-size="8pt"
                                                          font-family="Courier, monospace">
                                                    <xsl:value-of
                                                            select="format-number(TotalValue/Amount, '#,##0.00')"/>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- Percentage -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="right" font-size="8pt" font-weight="bold">
                                                    <xsl:choose>
                                                        <xsl:when test="TotalPercentage &gt; 5">
                                                            <xsl:attribute name="color">#dc3545</xsl:attribute>
                                                        </xsl:when>
                                                        <xsl:when test="TotalPercentage &gt; 2">
                                                            <xsl:attribute name="color">#ffc107</xsl:attribute>
                                                        </xsl:when>
                                                        <xsl:otherwise>
                                                            <xsl:attribute name="color">#28a745</xsl:attribute>
                                                        </xsl:otherwise>
                                                    </xsl:choose>
                                                    <xsl:value-of select="format-number(TotalPercentage, '0.00')"/>%
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- Market Value -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="right" font-size="8pt"
                                                          font-family="Courier, monospace">
                                                    <xsl:choose>
                                                        <xsl:when test="Account/MarketValue/Amount">
                                                            <xsl:value-of
                                                                    select="format-number(Account/MarketValue/Amount, '#,##0.00')"/>
                                                        </xsl:when>
                                                        <xsl:otherwise>N/A</xsl:otherwise>
                                                    </xsl:choose>
                                                </fo:block>
                                            </fo:table-cell>

                                            <!-- FX Rate -->
                                            <fo:table-cell border="0.5pt solid #dee2e6" padding="2mm">
                                                <fo:block text-align="center" font-size="7pt"
                                                          font-family="Courier, monospace">
                                                    <xsl:choose>
                                                        <xsl:when test="FXRates/FXRate">
                                                            <xsl:value-of
                                                                    select="format-number(FXRates/FXRate, '0.0000')"/>
                                                            <fo:inline font-size="6pt" color="#666666">
                                                                (<xsl:value-of select="FXRates/FXRate/@mulDiv"/>)
                                                            </fo:inline>
                                                        </xsl:when>
                                                        <xsl:otherwise>1.0000</xsl:otherwise>
                                                    </xsl:choose>
                                                </fo:block>
                                            </fo:table-cell>
                                        </fo:table-row>
                                    </xsl:for-each>
                                </fo:table-body>
                            </fo:table>

                            <!-- Fund Summary -->
                            <fo:block-container background-color="#f8f9fa" padding="4mm" border="1pt solid #dee2e6">
                                <fo:table table-layout="fixed" width="100%">
                                    <fo:table-column column-width="25%"/>
                                    <fo:table-column column-width="25%"/>
                                    <fo:table-column column-width="25%"/>
                                    <fo:table-column column-width="25%"/>
                                    <fo:table-body>
                                        <fo:table-row>
                                            <fo:table-cell padding="2mm">
                                                <fo:block text-align="center" font-size="8pt">
                                                    <fo:block color="#666666">TOP 5 CONCENTRATION</fo:block>
                                                    <fo:block font-weight="bold" color="#17a2b8" font-size="10pt">
                                                        <xsl:value-of
                                                                select="format-number(sum(FundDynamicData/Portfolios/Portfolio/Positions/Position[position() &lt;= 5]/TotalPercentage), '0.0')"/>%
                                                    </fo:block>
                                                </fo:block>
                                            </fo:table-cell>
                                            <fo:table-cell padding="2mm">
                                                <fo:block text-align="center" font-size="8pt">
                                                    <fo:block color="#666666">PORTFOLIO SUM</fo:block>
                                                    <fo:block font-weight="bold" color="#17a2b8" font-size="10pt">
                                                        <xsl:value-of
                                                                select="format-number(sum(FundDynamicData/Portfolios/Portfolio/Positions/Position/TotalPercentage), '0.0')"/>%
                                                    </fo:block>
                                                </fo:block>
                                            </fo:table-cell>
                                            <fo:table-cell padding="2mm">
                                                <fo:block text-align="center" font-size="8pt">
                                                    <fo:block color="#666666">FOREIGN CCY</fo:block>
                                                    <fo:block font-weight="bold" color="#17a2b8" font-size="10pt">
                                                        <xsl:value-of
                                                                select="count(FundDynamicData/Portfolios/Portfolio/Positions/Position[Currency != current()/Currency])"/>
                                                    </fo:block>
                                                </fo:block>
                                            </fo:table-cell>
                                            <fo:table-cell padding="2mm">
                                                <fo:block text-align="center" font-size="8pt">
                                                    <fo:block color="#666666">AVG POSITION SIZE</fo:block>
                                                    <fo:block font-weight="bold" color="#17a2b8" font-size="10pt">
                                                        <xsl:value-of
                                                                select="format-number(sum(FundDynamicData/Portfolios/Portfolio/Positions/Position/TotalPercentage) div count(FundDynamicData/Portfolios/Portfolio/Positions/Position), '0.00')"/>%
                                                    </fo:block>
                                                </fo:block>
                                            </fo:table-cell>
                                        </fo:table-row>
                                    </fo:table-body>
                                </fo:table>
                            </fo:block-container>
                        </fo:block-container>
                    </xsl:for-each>
                </fo:flow>
            </fo:page-sequence>
        </fo:root>
    </xsl:template>

    <!-- Key for currency grouping -->
    <xsl:key name="currencies" match="Position/Currency" use="."/>

</xsl:stylesheet>