package org.fxt.freexmltoolkit.controls.shell.editor;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Renders a {@link SchematronReportData} as a self-contained HTML document —
 * used by the {@link SchematronReportView}'s "Save Report" action. No external
 * resources (CSS/JS/fonts) so the saved file works anywhere, including offline.
 */
public final class SchematronReportHtml {

    private static final DateTimeFormatter TS = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    private SchematronReportHtml() {
    }

    /** Builds the complete HTML document for {@code data}. */
    public static String build(SchematronReportData data) {
        StringBuilder sb = new StringBuilder(8_192);
        long errors = data.errorCount();
        long warnings = data.warningCount();
        boolean pass = data.problems().isEmpty();

        sb.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n")
                .append("<title>Schematron Validation Report</title>\n<style>\n")
                .append("body{font-family:-apple-system,'Segoe UI',Roboto,sans-serif;margin:2em;color:#212529;}\n")
                .append("h1{font-size:1.5em;border-bottom:2px solid #1373D9;padding-bottom:.3em;}\n")
                .append("table.meta td{padding:.15em .8em .15em 0;color:#495057;}\n")
                .append("table.meta td:first-child{font-weight:600;}\n")
                .append(".chips{margin:1em 0;}\n")
                .append(".chip{display:inline-block;padding:.25em .9em;border-radius:1em;font-weight:600;margin-right:.6em;}\n")
                .append(".chip.pass{background:#d4edda;color:#155724;}\n")
                .append(".chip.error{background:#f8d7da;color:#721c24;}\n")
                .append(".chip.warning{background:#fff3cd;color:#856404;}\n")
                .append("table.findings{border-collapse:collapse;width:100%;margin-top:1em;}\n")
                .append("table.findings th,table.findings td{border:1px solid #dee2e6;padding:.45em .7em;")
                .append("text-align:left;vertical-align:top;font-size:.92em;}\n")
                .append("table.findings th{background:#f1f3f5;}\n")
                .append("tr.error td:first-child{color:#dc3545;font-weight:600;}\n")
                .append("tr.warning td:first-child{color:#b8860b;font-weight:600;}\n")
                .append("td.mono{font-family:ui-monospace,'Cascadia Code',Consolas,monospace;")
                .append("word-break:break-all;}\n")
                .append("footer{margin-top:2em;color:#868e96;font-size:.85em;}\n")
                .append("</style>\n</head>\n<body>\n");

        sb.append("<h1>Schematron Validation Report</h1>\n<table class=\"meta\">\n");
        if (data.documentName() != null && !data.documentName().isBlank()) {
            metaRow(sb, "Document", data.documentName());
        }
        if (data.schematronFile() != null) {
            metaRow(sb, "Schematron", data.schematronFile().getAbsolutePath());
        }
        metaRow(sb, "Generated", TS.format(LocalDateTime.now()));
        sb.append("</table>\n");

        sb.append("<div class=\"chips\">");
        if (pass) {
            sb.append("<span class=\"chip pass\">All rules passed</span>");
        } else {
            if (errors > 0) {
                sb.append("<span class=\"chip error\">").append(errors)
                        .append(errors == 1 ? " Error" : " Errors").append("</span>");
            }
            if (warnings > 0) {
                sb.append("<span class=\"chip warning\">").append(warnings)
                        .append(warnings == 1 ? " Warning" : " Warnings").append("</span>");
            }
        }
        sb.append("</div>\n");

        if (!pass) {
            sb.append("<table class=\"findings\">\n<tr><th>Severity</th><th>Line</th>")
                    .append("<th>Message</th><th>Rule / Test</th><th>Context (XPath)</th></tr>\n");
            for (ValidationProblem p : data.problems()) {
                String cls = "warning".equalsIgnoreCase(p.severity()) ? "warning" : "error";
                sb.append("<tr class=\"").append(cls).append("\">")
                        .append("<td>").append(escape(capitalize(p.severity()))).append("</td>")
                        .append("<td>").append(p.line() > 0 ? p.line() : "").append("</td>")
                        .append("<td>").append(escape(p.message())).append("</td>")
                        .append("<td class=\"mono\">").append(escape(nullSafe(p.ruleId()))).append("</td>")
                        .append("<td class=\"mono\">").append(escape(nullSafe(p.context()))).append("</td>")
                        .append("</tr>\n");
            }
            sb.append("</table>\n");
        }

        sb.append("<footer>Generated by FreeXmlToolkit</footer>\n</body>\n</html>\n");
        return sb.toString();
    }

    private static void metaRow(StringBuilder sb, String label, String value) {
        sb.append("<tr><td>").append(escape(label)).append("</td><td>")
                .append(escape(value)).append("</td></tr>\n");
    }

    private static String nullSafe(String s) {
        return s == null ? "" : s;
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) {
            return "Error";
        }
        return Character.toUpperCase(s.charAt(0)) + s.substring(1).toLowerCase(java.util.Locale.ROOT);
    }

    static String escape(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }
}
