/*
 * FreeXMLToolkit - Universal Toolkit for XML
 * Copyright (c) 2024-2025.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.fxt.freexmltoolkit.util;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.InputStream;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Properties;

/**
 * Central source of truth for application version and build metadata.
 *
 * <p>Resolution order:
 * <ol>
 *     <li>JAR manifest {@code Implementation-Version} (packaged builds)</li>
 *     <li>{@code build-info.properties} on the classpath (generated by Gradle, works in IDE)</li>
 *     <li>Hardcoded {@link #FALLBACK_VERSION} as last resort</li>
 * </ol>
 */
public final class VersionUtil {

    private static final Logger logger = LogManager.getLogger(VersionUtil.class);

    private static final String FALLBACK_VERSION = "0.0.0-dev";
    private static final String BUILD_INFO_RESOURCE = "/build-info.properties";

    private static final String VERSION;
    private static final String BUILD_TIMESTAMP;
    private static final String VENDOR;

    static {
        Properties props = loadBuildInfo();

        String manifestVersion = VersionUtil.class.getPackage().getImplementationVersion();
        String version = normalize(manifestVersion);
        if (version == null) {
            version = normalize(props.getProperty("version"));
        }
        VERSION = version != null ? version : FALLBACK_VERSION;

        BUILD_TIMESTAMP = props.getProperty("buildTimestamp", "");
        VENDOR = props.getProperty("vendor", "Karl Kauc");
    }

    private VersionUtil() {
    }

    /**
     * Application version (without leading "v"). Never {@code null}.
     */
    public static String getVersion() {
        return VERSION;
    }

    /**
     * Build timestamp in ISO-8601 (UTC), or an empty string if unavailable.
     */
    public static String getBuildTimestamp() {
        return BUILD_TIMESTAMP;
    }

    /**
     * Build timestamp formatted for human consumption (e.g. "2026-05-21 14:32 UTC"),
     * or an empty string if unavailable / unparseable.
     */
    public static String getBuildTimestampFormatted() {
        if (BUILD_TIMESTAMP == null || BUILD_TIMESTAMP.isBlank()) {
            return "";
        }
        try {
            OffsetDateTime odt = OffsetDateTime.parse(BUILD_TIMESTAMP);
            return odt.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'"));
        } catch (DateTimeParseException e) {
            return BUILD_TIMESTAMP;
        }
    }

    public static String getVendor() {
        return VENDOR;
    }

    private static Properties loadBuildInfo() {
        Properties props = new Properties();
        try (InputStream in = VersionUtil.class.getResourceAsStream(BUILD_INFO_RESOURCE)) {
            if (in != null) {
                props.load(in);
            } else {
                logger.debug("build-info.properties not found on classpath; using manifest/fallback");
            }
        } catch (Exception e) {
            logger.warn("Could not load build-info.properties: {}", e.getMessage());
        }
        return props;
    }

    private static String normalize(String version) {
        if (version == null || version.isBlank()) {
            return null;
        }
        return version.replaceFirst("^[vV]", "").trim();
    }
}
