package org.fxt.freexmltoolkit.controls.v2.xmleditor.serialization;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.fxt.freexmltoolkit.controls.v2.xmleditor.model.*;
import org.junit.jupiter.api.Test;

class XmlBlankLinesTest {

    @Test
    void testNoBlankLinesAfterRoundTrip() {
        String xml = """
                <?xml version="1.0" encoding="UTF-8"?>
                <FundsXML4 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xsi:noNamespaceSchemaLocation="https://fdp-service.oekb.at/FundsXML_4.1.10_AI.xsd">
                   <ControlData>
                      <UniqueDocumentID>EAM_7511019_20260130_FUND_1056</UniqueDocumentID>
                      <DocumentGenerated>2026-03-10T14:31:45</DocumentGenerated>
                      <ContentDate>2026-01-30</ContentDate>
                   </ControlData>
                </FundsXML4>
                """;

        XmlParser parser = new XmlParser();
        XmlSerializer serializer = new XmlSerializer();

        XmlDocument doc = parser.parse(xml);
        String serialized = serializer.serialize(doc);

        assertFalse(serialized.contains("\n\n"),
                "Serialized XML should not contain consecutive blank lines. Output:\n" + serialized);
    }

    @Test
    void testNoBlankLinesAfterTextEdit() {
        String xml = """
                <?xml version="1.0" encoding="UTF-8"?>
                <FundsXML4 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                           xsi:noNamespaceSchemaLocation="https://fdp-service.oekb.at/FundsXML_4.1.10_AI.xsd">
                   <ControlData>
                      <UniqueDocumentID>EAM_7511019_20260130_FUND_1056</UniqueDocumentID>
                      <DocumentGenerated>2026-03-10T14:31:45</DocumentGenerated>
                      <ContentDate>2026-01-30</ContentDate>
                   </ControlData>
                </FundsXML4>
                """;

        XmlParser parser = new XmlParser();
        XmlSerializer serializer = new XmlSerializer();

        XmlDocument doc = parser.parse(xml);
        XmlElement root = doc.getRootElement();
        XmlElement controlData = root.getChildElements().get(0);
        XmlElement uniqueDocId = controlData.getChildElements().get(0);

        // Simulate graphical edit: change text content
        var oldTextNodes = uniqueDocId.getChildren().stream()
                .filter(c -> c instanceof XmlText).toList();
        for (XmlNode t : oldTextNodes) {
            uniqueDocId.removeChild(t);
        }
        uniqueDocId.addChild(new XmlText("EAM_7511019_20260130_FUND_105"));

        String serialized = serializer.serialize(doc);

        assertFalse(serialized.contains("\n\n"),
                "After edit, serialized XML should not contain consecutive blank lines. Output:\n" + serialized);
        assertTrue(serialized.contains("EAM_7511019_20260130_FUND_105"),
                "Edited value should appear in output");
    }

    @Test
    void testWithCommentsAndBlankLinesInOriginal() {
        String xml = """
                <?xml version="1.0" encoding="UTF-8"?>
                <!--
                  Generated by FreeXmlToolkit v1.0.0
                  Date: 2026-03-20
                -->

                <FundsXML4 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="FundsXML4.xsd">
                <!-- Error comment -->
                  <ControlData>
                    <UniqueDocumentID>test-id</UniqueDocumentID>
                    <DocumentGenerated>2026-03-20T09:43:05</DocumentGenerated>
                  </ControlData>
                </FundsXML4>
                """;

        XmlParser parser = new XmlParser();
        XmlSerializer serializer = new XmlSerializer();

        XmlDocument doc = parser.parse(xml);
        String serialized = serializer.serialize(doc);

        assertFalse(serialized.contains("\n\n\n"),
                "Should not have triple newlines. Output:\n" + serialized);
    }

    @Test
    void testWith3SpaceIndentation() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<FundsXML4 xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +
                "           xsi:noNamespaceSchemaLocation=\"https://fdp-service.oekb.at/FundsXML_4.1.10_AI.xsd\">\n" +
                "   <ControlData>\n" +
                "      <UniqueDocumentID>EAM_7511019_20260130_FUND_1056</UniqueDocumentID>\n" +
                "      <DocumentGenerated>2026-03-10T14:31:45</DocumentGenerated>\n" +
                "      <ContentDate>2026-01-30</ContentDate>\n" +
                "   </ControlData>\n" +
                "</FundsXML4>";

        XmlParser parser = new XmlParser();
        XmlSerializer serializer = new XmlSerializer();

        XmlDocument doc = parser.parse(xml);
        String serialized = serializer.serialize(doc);

        assertFalse(serialized.contains("\n\n"),
                "Should not have blank lines. Output:\n" + serialized);
    }

    @Test
    void testSerializeRespectsIndentSize() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<root>\n" +
                "  <child>\n" +
                "    <grandchild>value</grandchild>\n" +
                "  </child>\n" +
                "</root>";

        XmlParser parser = new XmlParser();
        XmlDocument doc = parser.parse(xml);

        // Serialize with indent size 4
        String serialized4 = doc.serialize(0, 4);
        assertTrue(serialized4.contains("    <child>"), "Level 1 should be 4 spaces. Got:\n" + serialized4);
        assertTrue(serialized4.contains("        <grandchild>"), "Level 2 should be 8 spaces. Got:\n" + serialized4);
        assertFalse(serialized4.contains("\n\n"), "Should have no blank lines");

        // Serialize with indent size 3
        String serialized3 = doc.serialize(0, 3);
        assertTrue(serialized3.contains("   <child>"), "Level 1 should be 3 spaces. Got:\n" + serialized3);
        assertTrue(serialized3.contains("      <grandchild>"), "Level 2 should be 6 spaces. Got:\n" + serialized3);
    }

    @Test
    void testSerializerUsesConfiguredIndentSize() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<root>\n" +
                "  <child>value</child>\n" +
                "</root>";

        XmlParser parser = new XmlParser();
        XmlDocument doc = parser.parse(xml);

        // Serializer with indent size 4
        XmlSerializer serializer4 = new XmlSerializer(4);
        String result = serializer4.serialize(doc);
        assertTrue(result.contains("    <child>"), "Serializer should use indent size 4. Got:\n" + result);

        // Serializer with indent size 3
        XmlSerializer serializer3 = new XmlSerializer(3);
        String result3 = serializer3.serialize(doc);
        assertTrue(result3.contains("   <child>"), "Serializer should use indent size 3. Got:\n" + result3);
    }

    @Test
    void testWithRealFile() throws IOException {
        Path realFile = Path.of("/home/karl/FreeXmlToolkit/HRICAMUSEEB4-2026-02-27.xml");
        if (!Files.exists(realFile)) {
            return;
        }

        String xml = Files.readString(realFile);

        XmlParser parser = new XmlParser();
        XmlSerializer serializer = new XmlSerializer();

        XmlDocument doc = parser.parse(xml);

        // Simulate an edit
        XmlElement root = doc.getRootElement();
        XmlElement controlData = root.getChildElements().get(0);
        XmlElement uniqueDocId = controlData.getChildElements().get(0);
        var oldTextNodes = uniqueDocId.getChildren().stream()
                .filter(c -> c instanceof XmlText).toList();
        for (XmlNode t : oldTextNodes) {
            uniqueDocId.removeChild(t);
        }
        uniqueDocId.addChild(new XmlText("EDITED_VALUE"));

        String serialized = serializer.serialize(doc);

        assertFalse(serialized.contains("\n\n"),
                "Real file: Should not have blank lines after edit");
    }
}
