/*
 * FreeXMLToolkit - Universal Toolkit for XML
 * Copyright (c) Karl Kauc 2024.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 */

package org.fxt.freexmltoolkit.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for ExportMetadataService.
 * Tests metadata generation, duplicate prevention, and format-specific outputs.
 */
class ExportMetadataServiceTest {

    private ExportMetadataService metadataService;
    private PropertiesService mockPropertiesService;

    @BeforeEach
    void setUp() {
        mockPropertiesService = mock(PropertiesService.class);
        metadataService = new ExportMetadataService(mockPropertiesService);
    }

    // === Basic getter tests ===

    @Test
    @DisplayName("getAppName returns FreeXmlToolkit")
    void testGetAppName() {
        assertEquals("FreeXmlToolkit", metadataService.getAppName());
    }

    @Test
    @DisplayName("getAppVersion returns a version string")
    void testGetAppVersion() {
        String version = metadataService.getAppVersion();
        assertNotNull(version);
        assertFalse(version.isEmpty());
        // Should match version pattern like "1.0.0" or similar
        assertTrue(version.matches("\\d+\\.\\d+\\.\\d+.*") || version.equals("1.0.0"));
    }

    @Test
    @DisplayName("getAppNameWithVersion returns combined name and version")
    void testGetAppNameWithVersion() {
        String result = metadataService.getAppNameWithVersion();
        assertTrue(result.startsWith("FreeXmlToolkit v"));
    }

    @Test
    @DisplayName("getTimestamp returns ISO-8601 format")
    void testGetTimestamp() {
        String timestamp = metadataService.getTimestamp();
        assertNotNull(timestamp);
        // Should match ISO-8601 local date-time pattern
        assertTrue(timestamp.matches("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}.*"));
    }

    // === User data tests ===

    @Test
    @DisplayName("getUserName returns user name from settings")
    void testGetUserName_withValue() {
        when(mockPropertiesService.get("user.name")).thenReturn("John Doe");
        assertEquals("John Doe", metadataService.getUserName());
    }

    @Test
    @DisplayName("getUserName returns null for empty value")
    void testGetUserName_empty() {
        when(mockPropertiesService.get("user.name")).thenReturn("");
        assertNull(metadataService.getUserName());
    }

    @Test
    @DisplayName("getUserName returns null for blank value")
    void testGetUserName_blank() {
        when(mockPropertiesService.get("user.name")).thenReturn("   ");
        assertNull(metadataService.getUserName());
    }

    @Test
    @DisplayName("getUserCompany returns company from settings")
    void testGetUserCompany_withValue() {
        when(mockPropertiesService.get("user.company")).thenReturn("ACME Corp");
        assertEquals("ACME Corp", metadataService.getUserCompany());
    }

    @Test
    @DisplayName("getUserCompany returns null for null value")
    void testGetUserCompany_null() {
        when(mockPropertiesService.get("user.company")).thenReturn(null);
        assertNull(metadataService.getUserCompany());
    }

    // === XML comment generation tests ===

    @Test
    @DisplayName("generateXmlComment includes app name and version")
    void testGenerateXmlComment_containsAppInfo() {
        String comment = metadataService.generateXmlComment();
        assertTrue(comment.contains("Generated by FreeXmlToolkit"));
        assertTrue(comment.contains("Date:"));
        assertTrue(comment.startsWith("\n<!--"));
        assertTrue(comment.endsWith("-->\n"));
    }

    @Test
    @DisplayName("generateXmlComment includes user name when set")
    void testGenerateXmlComment_withUserName() {
        when(mockPropertiesService.get("user.name")).thenReturn("John Doe");
        String comment = metadataService.generateXmlComment();
        assertTrue(comment.contains("Author: John Doe"));
    }

    @Test
    @DisplayName("generateXmlComment excludes user name when empty")
    void testGenerateXmlComment_withoutUserName() {
        when(mockPropertiesService.get("user.name")).thenReturn("");
        String comment = metadataService.generateXmlComment();
        assertFalse(comment.contains("Author:"));
    }

    @Test
    @DisplayName("generateXmlComment includes company when set")
    void testGenerateXmlComment_withCompany() {
        when(mockPropertiesService.get("user.company")).thenReturn("ACME Corp");
        String comment = metadataService.generateXmlComment();
        assertTrue(comment.contains("Company: ACME Corp"));
    }

    // === HTML meta tags tests ===

    @Test
    @DisplayName("generateHtmlMetaTags includes generator meta tag")
    void testGenerateHtmlMetaTags_containsGenerator() {
        String metaTags = metadataService.generateHtmlMetaTags();
        assertTrue(metaTags.contains("<meta name=\"generator\""));
        assertTrue(metaTags.contains("FreeXmlToolkit"));
    }

    @Test
    @DisplayName("generateHtmlMetaTags includes author when set")
    void testGenerateHtmlMetaTags_withAuthor() {
        when(mockPropertiesService.get("user.name")).thenReturn("John Doe");
        String metaTags = metadataService.generateHtmlMetaTags();
        assertTrue(metaTags.contains("<meta name=\"author\" content=\"John Doe\">"));
    }

    @Test
    @DisplayName("generateHtmlMetaTags escapes HTML special characters")
    void testGenerateHtmlMetaTags_escapesHtml() {
        when(mockPropertiesService.get("user.name")).thenReturn("John <script>alert('xss')</script> Doe");
        String metaTags = metadataService.generateHtmlMetaTags();
        assertFalse(metaTags.contains("<script>"));
        assertTrue(metaTags.contains("&lt;script&gt;"));
    }

    // === JSON metadata tests ===

    @Test
    @DisplayName("generateJsonMetadata includes all fields")
    void testGenerateJsonMetadata() {
        when(mockPropertiesService.get("user.name")).thenReturn("John Doe");
        when(mockPropertiesService.get("user.company")).thenReturn("ACME Corp");

        String json = metadataService.generateJsonMetadata();
        assertTrue(json.contains("\"_metadata\""));
        assertTrue(json.contains("\"generator\": \"FreeXmlToolkit\""));
        assertTrue(json.contains("\"author\": \"John Doe\""));
        assertTrue(json.contains("\"company\": \"ACME Corp\""));
        assertTrue(json.contains("\"generatedAt\""));
    }

    @Test
    @DisplayName("generateJsonMetadata omits empty fields")
    void testGenerateJsonMetadata_omitsEmptyFields() {
        when(mockPropertiesService.get("user.name")).thenReturn(null);
        when(mockPropertiesService.get("user.company")).thenReturn("");

        String json = metadataService.generateJsonMetadata();
        assertFalse(json.contains("\"author\""));
        assertFalse(json.contains("\"company\""));
    }

    // === Duplicate prevention tests ===

    @Test
    @DisplayName("hasExistingMetadata returns true for content with metadata")
    void testHasExistingMetadata_withMetadata() {
        String xml = """
            <?xml version="1.0" encoding="UTF-8"?>
            <!--
              Generated by FreeXmlToolkit v1.0.0
              Author: Test User
              Date: 2025-12-10T14:30:00
            -->
            <root/>
            """;
        assertTrue(metadataService.hasExistingMetadata(xml));
    }

    @Test
    @DisplayName("hasExistingMetadata returns false for content without metadata")
    void testHasExistingMetadata_withoutMetadata() {
        String xml = """
            <?xml version="1.0" encoding="UTF-8"?>
            <root/>
            """;
        assertFalse(metadataService.hasExistingMetadata(xml));
    }

    @Test
    @DisplayName("hasExistingMetadata returns false for null content")
    void testHasExistingMetadata_null() {
        assertFalse(metadataService.hasExistingMetadata(null));
    }

    @Test
    @DisplayName("hasExistingMetadata returns false for empty content")
    void testHasExistingMetadata_empty() {
        assertFalse(metadataService.hasExistingMetadata(""));
    }

    @Test
    @DisplayName("removeExistingMetadata removes metadata comment")
    void testRemoveExistingMetadata() {
        String xml = """
            <?xml version="1.0" encoding="UTF-8"?>
            <!--
              Generated by FreeXmlToolkit v1.0.0
              Author: Test User
              Date: 2025-12-10T14:30:00
            -->
            <root/>
            """;
        String result = metadataService.removeExistingMetadata(xml);
        assertFalse(result.contains("Generated by FreeXmlToolkit"));
        assertTrue(result.contains("<root/>"));
        assertTrue(result.contains("<?xml"));
    }

    @Test
    @DisplayName("removeExistingMetadata preserves other comments")
    void testRemoveExistingMetadata_preservesOtherComments() {
        String xml = """
            <?xml version="1.0" encoding="UTF-8"?>
            <!--
              Generated by FreeXmlToolkit v1.0.0
            -->
            <!-- This is a user comment -->
            <root/>
            """;
        String result = metadataService.removeExistingMetadata(xml);
        assertFalse(result.contains("Generated by FreeXmlToolkit"));
        assertTrue(result.contains("This is a user comment"));
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata adds metadata to content without existing metadata")
    void testAddOrUpdateXmlMetadata_addsNew() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<root/>";
        String result = metadataService.addOrUpdateXmlMetadata(xml);

        assertTrue(result.contains("Generated by FreeXmlToolkit"));
        assertTrue(result.contains("<root/>"));
        // Metadata should appear after XML declaration
        int xmlDeclEnd = result.indexOf("?>");
        int metadataStart = result.indexOf("Generated by FreeXmlToolkit");
        assertTrue(metadataStart > xmlDeclEnd);
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata prevents duplicate metadata")
    void testAddOrUpdateXmlMetadata_preventsDuplicate() {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<root/>";

        // Add metadata first time
        String result1 = metadataService.addOrUpdateXmlMetadata(xml);
        assertTrue(result1.contains("Generated by FreeXmlToolkit"));

        // Add metadata second time - should NOT create duplicate
        String result2 = metadataService.addOrUpdateXmlMetadata(result1);

        // Count occurrences of "Generated by FreeXmlToolkit"
        Pattern pattern = Pattern.compile("Generated by FreeXmlToolkit");
        Matcher matcher = pattern.matcher(result2);
        int count = 0;
        while (matcher.find()) {
            count++;
        }

        assertEquals(1, count, "Should have exactly one metadata comment, found: " + count);
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata handles content without XML declaration")
    void testAddOrUpdateXmlMetadata_withoutXmlDeclaration() {
        String xml = "<root><child/></root>";
        String result = metadataService.addOrUpdateXmlMetadata(xml);

        assertTrue(result.contains("Generated by FreeXmlToolkit"));
        assertTrue(result.contains("<root>"));
        // Metadata should be at the beginning
        assertTrue(result.trim().startsWith("\n<!--") || result.trim().startsWith("<!--"));
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata updates timestamp on re-save")
    void testAddOrUpdateXmlMetadata_updatesTimestamp() throws InterruptedException {
        String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<root/>";

        String result1 = metadataService.addOrUpdateXmlMetadata(xml);

        // Extract first timestamp
        Pattern datePattern = Pattern.compile("Date: (\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2})");
        Matcher matcher1 = datePattern.matcher(result1);
        assertTrue(matcher1.find());
        String timestamp1 = matcher1.group(1);

        // Wait a bit to ensure timestamp changes
        Thread.sleep(1100);

        // Update metadata
        String result2 = metadataService.addOrUpdateXmlMetadata(result1);

        // Extract second timestamp
        Matcher matcher2 = datePattern.matcher(result2);
        assertTrue(matcher2.find());
        String timestamp2 = matcher2.group(1);

        // Timestamps should be different
        assertNotEquals(timestamp1, timestamp2, "Timestamp should be updated on re-save");
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata returns null for null input")
    void testAddOrUpdateXmlMetadata_nullInput() {
        assertNull(metadataService.addOrUpdateXmlMetadata(null));
    }

    @Test
    @DisplayName("addOrUpdateXmlMetadata returns empty for empty input")
    void testAddOrUpdateXmlMetadata_emptyInput() {
        assertEquals("", metadataService.addOrUpdateXmlMetadata(""));
    }

    // === SVG metadata tests ===

    @Test
    @DisplayName("generateSvgMetadata includes Dublin Core elements")
    void testGenerateSvgMetadata() {
        when(mockPropertiesService.get("user.name")).thenReturn("John Doe");
        when(mockPropertiesService.get("user.company")).thenReturn("ACME Corp");

        String svg = metadataService.generateSvgMetadata();

        assertTrue(svg.contains("<metadata>"));
        assertTrue(svg.contains("</metadata>"));
        assertTrue(svg.contains("xmlns:dc=\"http://purl.org/dc/elements/1.1/\""));
        assertTrue(svg.contains("<dc:source>FreeXmlToolkit"));
        assertTrue(svg.contains("<dc:creator>John Doe</dc:creator>"));
        assertTrue(svg.contains("<dc:publisher>ACME Corp</dc:publisher>"));
        assertTrue(svg.contains("<dc:date>"));
    }

    @Test
    @DisplayName("generateSvgMetadata omits empty creator and publisher")
    void testGenerateSvgMetadata_omitsEmptyFields() {
        when(mockPropertiesService.get("user.name")).thenReturn(null);
        when(mockPropertiesService.get("user.company")).thenReturn("");

        String svg = metadataService.generateSvgMetadata();

        assertFalse(svg.contains("<dc:creator>"));
        assertFalse(svg.contains("<dc:publisher>"));
        assertTrue(svg.contains("<dc:source>")); // Source is always included
    }
}
